import styles from '../styles/Home.module.css'

import Head from 'next/head'
import FlightsContainer from '../components/FlightsContainer'

import { server } from '../config'

export default function Home({ data }) {
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Skyscanner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img className={styles.logo} src="/skyscannerLogo.png" alt="Skyscanner" />
      <FlightsContainer flights={data} />
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`${server}/api/flights`)
  const data = await res.json()

  return {
    props: { data }
  }
}